version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass123

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass123
      ME_CONFIG_MONGODB_SERVER: mongodb # This is the name of the mongo container
      ME_CONFIG_BASICAUTH: false

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
